[workspace.package]
edition = "2021"
license = "MIT"
homepage = "https://github.com/edger-dev/dioxus-class"
repository = "https://github.com/edger-dev/dioxus-class"

[workspace]
members = [
    "crates/dioxus-class",
    "crates/dioxus-tailwindcss",
    "crates/dioxus-daisyui",
]

[workspace.dependencies]
dioxus = "0.3.1"
dioxus-class = { path = "crates/dioxus-class", version = "0.2.1" }
dioxus-tailwindcss = { path = "crates/dioxus-tailwindcss", version = "0.2.1" }
dioxus-daisyui = { path = "crates/dioxus-daisyui", version = "0.2.1" }

paste = "1.0.11"

[package]
publish = false
version = "0.0.0"
name = "examples"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dev-dependencies]
dioxus-class = { workspace = true }
dioxus-tailwindcss = { workspace = true }
dioxus = { workspace = true }

im-rc = "15.1"
dioxus-desktop = "0.3"
lazy_static = "1.4.0"