[package]
name = "dioxus-tailwindcss"
version = "0.2.0"
edition = "2021"
license = "MIT"
homepage = "https://www.edger.dev"
repository = "https://github.com/edger-dev/dioxus-tailwindcss"
description = "Dioxus tailwindcss"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { workspace = true }
dioxus-class = { workspace = true }
paste = { workspace = true }
